name: conversa

on:
  push:
    branches:
      - main

jobs:
  escrever-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Nosso primeiro workflow
        run: echo "Nosso primeiro workflow"